name: RSpec and Rubocop

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: RSpec
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true
      - name: Run rspec
        run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
